extends RefCounted

const TEXT_EN := {
	# Shared relationship navigation.
	"중앙홀로": "To the Central Hall",
	"작업 회랑으로 · 진행 보존": "To the Work Hall · Progress Saved",
	"온실로 · 진행 보존": "To the Greenhouse · Progress Saved",
	"주방으로 · 진행 보존": "To the Kitchen · Progress Saved",
	"대시계로 · 진행 보존": "To the Great Clock · Progress Saved",
	"입구로 · 진행 보존": "To the Entrance · Progress Saved",
	"색분해실로 · 진행 보존": "To the Color-Separation Room · Progress Saved",
	"아직 결정하지 않는다": "Do Not Decide Yet",
	"다시 펼친다": "Lay Them Out Again",
	"순서 검증": "Verify Order",
	"확인함": "Inspected",
	"확인": "Checked",
	"미배치": "Unassigned",
	"결손": "Missing",
	"선": "Line",
	"점": "Dot",
	"호": "Arc",

	# Mara 1 UI.
	"마라 1 · 끊긴 배선과 삭제 기록": "Mara 1 · Severed Wiring and Deleted Records",
	"사용인 작업 회랑": "Servants' Work Hall",
	"마라 1이 스패너로 배선 덮개를 붙든다.\n마른 종이 냄새가 난다. '이건... 닦는 걸로 끝나지 않겠슴다.'": "Mara 1 holds a wiring cover open with her spanner.\nThe air smells of dry paper. 'This one... isn't going away with a bit of cleaning.'",
	"배선실로": "To the Wiring Room",
	"배선실": "Wiring Room",
	"기록을 보존했다. 사건과 명령자·수행자의 책임은 남아 있다.\n수첩에서 REC_MARA1을 다시 확인할 수 있다.": "The record has been preserved. The incident and the responsibility of both commander and operator remain.\nREC_MARA1 can be reviewed in the notebook.",
	"패널과 세 단자의 신호를 조사한다": "Inspect the Panel and Three Terminal Signals",
	"대각 나사선 · 솔 마찰음": "Diagonal Screw Line · Brush Friction",
	"손바닥 승인각 · 두 번 확인음": "Palm Approval Angle · Two Confirmation Tones",
	"끊긴 사각 · 늦은 경고음": "Broken Square · Delayed Warning Tone",
	"출처 확인함": "Source Identified",
	"스패너로 가짜 브리지를 해제한다": "Remove the False Bridge with the Spanner",
	"날짜와 문서 참조, 닦임 방향을 대조해 파편을 순서대로 놓는다.": "Order the fragments by comparing dates, document references, and wipe direction.",
	"파편을 다시 펼친다": "Lay Out the Fragments Again",
	"기록 순서를 검증한다": "Verify the Record Order",
	"마라 1의 이야기를 듣는다": "Hear Mara 1's Account",
	"기록 보존 방식을 정한다": "Choose How to Preserve the Record",
	"기록을 어떻게 남길까": "How Should the Record Remain?",
	"두 방식 모두 사건과 명령자·수행자의 책임을 보존한다.": "Both methods preserve the incident and the responsibility of its commander and operator.",
	"책임자와 원문을 그대로 남긴다": "Keep the Original Text and All Responsible Names",
	"피해자 식별 정보만 보호한다": "Protect Only the Victims' Identifying Information",

	# Iris UI.
	"이리스 · 계절 센서와 빼앗긴 전력": "Iris · Seasonal Sensors and Diverted Power",
	"온실": "Greenhouse",
	"빛은 따뜻하지만 공기는 차갑다.\n흙은 젖지 않은 채 젖은 냄새만 난다. 이리스가 웃는다. '안쪽을 보실래요?'": "The light is warm, but the air is cold.\nThe soil is dry yet smells wet. Iris smiles. 'Would you like to see inside?'",
	"계절 제어실로": "To the Climate Control Room",
	"계절 제어실": "Climate Control Room",
	"외부값의 결손과 승인 도용 기록을 보존했다.\n수첩에서 REC_IRIS를 확인할 수 있다.": "The missing external readings and credential misuse have been preserved.\nREC_IRIS can be reviewed in the notebook.",
	"세 계기와 입력 출처를 조사한다": "Inspect the Three Gauges and Their Input Sources",
	"온도": "Temperature",
	"습도": "Humidity",
	"광량": "Light Level",
	"꽃잎 문양 · 매끄러운 반복 주기": "Petal Glyph · Smooth Repeating Cycle",
	"유리 진동 · 불규칙 파형 · 일부 측정 결손": "Glass Vibration · Irregular Waveform · Missing Measurements",
	"후광 문양 · 오래된 날짜 · 고정된 과거값": "Halo Glyph · Old Date · Fixed Historical Value",
	"날짜와 앞 문서의 참조로 전력 기록을 연결한다.": "Connect the power records using their dates and references to prior documents.",
	"경고 제출자: 이리스": "Warning submitted by: Iris",
	"명령 실행자: 아버지 / 사용 자격: 이리스": "Command executed by: Father / Credential used: Iris",
	"감사 책임자: 이리스": "Audit responsibility: Iris",
	"무엇이 어긋났는가?": "What does not match?",
	"경고가 승인으로 바뀌었다": "The Warning Was Changed into Approval",
	"자격 소유자를 실행자로 기록했다": "The Credential Owner Was Recorded as the Executor",
	"이리스의 이야기를 듣는다": "Hear Iris's Account",
	"기록과 현재 온실을 어떻게 둘까": "Choose What to Preserve in the Record and Greenhouse",
	"문양과 날짜를 다시 본다": "Review the Glyphs and Dates",
	"투사 연출": "Projection",
	"외부 센서": "External Sensor",
	"기억 모델": "Memory Model",
	"입력 출처": "Input Source",
	"꽃잎의 반복 / 유리의 결손 파형 / 후광의 과거 날짜를 대조한다.": "Compare the repeating petals, incomplete glass waveform, and old date in the halo.",
	"지금의 온실": "The Greenhouse as It Is Now",
	"두 방식 모두 외부값과 책임 기록을 보존한다. 현재 보이는 계절 연출을 유지할지 정한다.": "Both methods preserve the external readings and responsibility record. Decide whether to retain the current seasonal projection.",
	"불완전한 외부값과 책임 로그를 그대로 남긴다": "Keep the Incomplete External Readings and Responsibility Log as They Are",
	"외부값은 보존하고 현재 온실 연출은 유지한다": "Preserve the External Readings and Retain the Current Greenhouse Projection",

	# Luca UI.
	"루카 · 생명 유지 장치와 유예된 기상": "Luca · Life Support and Deferred Awakening",
	"주방": "Kitchen",
	"조리대 아래의 배관이 손목과 비슷한 주기로 뛴다.\n루카가 문을 연다. '이번에는... 아가씨 기준부터 볼게요.'": "The pipes beneath the counter pulse at almost the same rhythm as my wrist.\nLuca opens the door. 'This time... we'll start with your readings.'",
	"생명 유지실로": "To the Life Support Room",
	"생명 유지실": "Life Support Room",
	"현재 생존 신호는 유지된다. 기상 안전은 확정되지 않았다.\n수첩에서 REC_LUCA를 다시 확인할 수 있다.": "Current vital signs are stable. The safety of awakening remains unconfirmed.\nREC_LUCA can be reviewed in the notebook.",
	"배관의 맥박과 진단 패널 조사": "Inspect the Pipe Pulses and Diagnostic Panel",
	"장식 매듭 · 맥박 없음": "Decorative Knot · No Pulse",
	"BIO MAIN · 굵은 이중 맥박": "BIO MAIN · Strong Paired Pulse",
	"AUX · 점선 한 번 응답": "AUX · One Dotted Response",
	"연결 선택": "Selected for Connection",
	"선택한 두 관을 진단 패널에 연결": "Connect the Two Selected Pipes to the Diagnostic Panel",
	"두 번의 주관 맥박 → 보조관 응답 → 안전 밸브": "Two Main Pulses -> Auxiliary Response -> Safety Valve",
	"시간 제한은 없다. 배치한 주기를 언제든 미리 확인할 수 있다.": "There is no time limit. The arranged cycle can be previewed at any time.",
	"전체 주기 미리 확인": "Preview Full Cycle",
	"주기 실행과 안전 밸브 확인": "Run Cycle and Check Safety Valve",
	"루카의 이야기를 듣는다": "Hear Luca's Account",
	"위험 기록을 읽을 순서를 정한다": "Choose the Order for Reading the Risk Record",
	"아직 배치하지 않는다": "Do Not Assign Yet",
	"주관 맥박 1": "Main Pulse 1",
	"주관 맥박 2": "Main Pulse 2",
	"보조관 응답 1": "Auxiliary Response 1",
	"안전 밸브 확인": "Safety Valve Check",
	"밸브 위상": "Valve Phase",
	"시간이 아니라 순서를 맞춘다. 전체 주기는 미리 확인할 수 있다.": "Match the order, not the timing. The full cycle can be previewed.",
	"확인할 순서": "Order of Disclosure",
	"두 선택 모두 같은 위험 기록을 읽는다. 지금 생존한다는 사실이 기상 안전을 보장하지는 않는다.": "Both choices reveal the same risk record. Being alive now does not guarantee that awakening is safe.",
	"위험 수치를 먼저 전부 읽는다": "Read All Risk Values First",
	"장치를 안정시킨 뒤 기록을 함께 읽는다": "Stabilize the System, Then Read the Record Together",

	# Edgar UI.
	"에드가 · 보안 코어와 선택 권한": "Edgar · Security Core and Authority to Choose",
	"대시계": "Great Clock",
	"대시계 뒤 수직 잠금선이 드러난다.\n에드가가 레이피어로 네 선의 경계를 짚는다. '확인하실 기록이 있습니다.'": "Vertical locking lines appear behind the great clock.\nEdgar traces the boundary of all four with his rapier. 'There are records you should inspect.'",
	"보안 기계실로": "To the Security Machine Room",
	"대시계 기계실": "Great Clock Machine Room",
	"선택권은 SUBJECT, 주인공에게 있다.\n수첩의 REC_EDGAR에서 책임 기록을 확인할 수 있다.": "The authority to choose belongs to SUBJECT, the Protagonist.\nThe responsibility record can be reviewed in REC_EDGAR.",
	"네 권한 변경 이력을 선행 사건 순서로 놓는다.": "Arrange the four authority changes in the order of their preceding events.",
	"현재 권한 배치 검증": "Verify Current Authority Assignment",
	"명령과 에드가의 결정을 대조한다": "Compare the Command with Edgar's Decision",
	"책임을 남길 방식을 정한다": "Choose How to Record Responsibility",
	"근거를 다시 읽는다": "Review the Evidence",
	"책임의 기록": "Record of Responsibility",
	"두 선택 모두 현재 선택권은 주인공에게 반환된다. 용서 여부나 엔딩을 결정하는 선택이 아니다.": "Both choices return present authority to the Protagonist. This choice determines neither forgiveness nor the ending.",
	"기록을 다시 읽는다": "Read the Record Again",
	"당신이 한 결정도 공식 기록에 남겨요.": "Put Your Own Decision in the Official Record.",
	"기록보다 먼저, 내 권한을 내게 직접 돌려줘요.": "Before the Record, Return My Authority Directly to Me.",

	# Mara 2 UI.
	"마라 2 · 원본과 분산된 주석": "Mara 2 · The Original and Its Distributed Annotations",
	"북쪽 기록 회랑": "North Archive Hall",
	"색분해실 입구": "Color-Separation Room Entrance",
	"마라 2가 이중 윤곽의 이름표를 바로 세운다.\n'천재의 작업실에 온 걸 환영해요! 손대다 망가뜨려도 제 탓은 아니고요!'": "Mara 2 straightens a nameplate with a doubled outline.\n'Welcome to a genius's workshop! If you break something by touching it, that's definitely not my fault!'",
	"안쪽으로": "Go Inside",
	"회랑으로": "To the Hall",
	"색분해실": "Color-Separation Room",
	"이 시점의 조각 놓기": "Place This Moment's Fragment",
	"3음 시작점": "Three-Tone Start Point",
	"이중 윤곽 기준점": "Double-Outline Reference Point",
	"시점 순서 다시 놓기": "Reset the Moment Order",
	"기록 중첩 검증": "Verify Record Overlay",
	"세 시점 모두 같은 3·7·11칸이 비어 있다.\n마라 2가 먼저 문을 연다. 뒤돌아보지 않는다.": "The same cells, 3, 7, and 11, are empty in all three moments.\nMara 2 opens the door first and does not look back.",
	"인격 아카이브로": "To the Personality Archive",
	"인격 아카이브": "Personality Archive",
	"원본과 감정 주석을 보존했다.\n수첩에서 REC_MARA2를 확인할 수 있다.": "The original and its emotional annotations have been preserved.\nREC_MARA2 can be reviewed in the notebook.",
	"보조 영역": "Backup Region",
	"12칸 체크섬 비교": "Compare the 12-Cell Checksum",
	"자기 저장 영역 양도 기록을 듣는다": "Hear the Record of Her Donated Storage",
	"원본과 주석 보존 방식": "Choose How to Preserve the Original and Annotations",
	"문양을 다시 본다": "Review the Glyph",
	"표식을 다시 본다": "Review the Marks",
	"3음 시작 표식과 이중 윤곽 기준선을 맞춘다.": "Align the three-tone start mark with the double-outline reference line.",
	"보조 기록을 다시 본다": "Review the Backup Records",
	"원본 참조가 같은 조각을 대조한다.": "Compare fragments that share the same original reference.",
	"기록의 보존": "Preserving the Record",
	"둘 다 원본과 감정 주석을 보존한다. 병합은 완전 회복의 약속이 아니며, 분리는 포기가 아니다.": "Both preserve the original and its emotional annotations.\nMerging does not promise full recovery, and separation is not abandonment.",
	"설명을 다시 생각한다": "Think Over the Explanation",
	"감정 주석을 원본에 다시 합친다.": "Merge the Emotional Annotations Back into the Original.",
	"원본과 주석을 분리해 서로 참조하게 한다.": "Keep the Original and Annotations Separate with Cross-References.",

	# Data labels and records.
	"전환 전날 · 승인 원본 / 손바닥 승인각\n미래에 새 육체로 살아갈 것이라는 약속. 원래 신체 소실과 생체 신경 코어 결합 전환의 고지란은 비어 있다. 다음 장으로 이어지는 대각 닦임이 아래로 향한다.": "Day before conversion · Original approval / Palm approval angle\nA promise of life in a new body. The disclosure fields for loss of the original body and conversion into a bio-neural core are blank. A diagonal wipe leading to the next page points downward.",
	"전환 당일 · 앞 승인 원본 참조 / 끊긴 사각\n전환 실험 실패 발생. 고지되지 않은 절차가 실행됐다. 윗쪽 닦임이 승인 원본의 아랫쪽과 이어진다. 일부 피해자 이름은 열 손상으로 읽히지 않는다.": "Day of conversion · References prior approval / Broken square\nConversion experiment failure. An undisclosed procedure was executed. The upper wipe connects to the lower edge of the original approval. Heat damage has made some victims' names unreadable.",
	"실패 보고 직후 · 실패 보고 참조 / 대각 나사선\n아버지의 명령: '운영 안정성을 위해 정리.' 수행자: 마라 1. 실패 로그와 동의 절차 모순을 정비 이력으로 덮음.": "Immediately after failure report · References failure report / Diagonal screw line\nFather's order: 'Clean up for operational stability.' Operator: Mara 1. The failure log and contradictions in consent procedure were covered by maintenance history.",
	"최초 경고 / 이리스: 두 시설을 함께 살릴 전력이 없다. 이 문서는 승인서가 아니다.": "Initial warning / Iris: There is not enough power to save both facilities. This document is not an approval.",
	"경고 접수 뒤 / 냉각 우선 명령. 실행자: 아버지. 사용 자격: 이리스 관리자. 경고 서명과 실행 승인 서명이 다르다.": "After warning received / Cooling-priority order. Executor: Father. Credential used: Iris, administrator. The warning and execution signatures differ.",
	"명령 실행 뒤 / 생태 샘플 보관고와 복구 온실 일부 정지. 전력은 주인공 냉각 장치로 이동.": "After command execution / Ecological sample storage and part of the restoration greenhouse shut down. Power moved to the Protagonist's cooling unit.",
	"차단 결과 수신 뒤 / 자동 감사: 최종 승인 책임자 이리스. 명령 실행자와 책임자 필드가 일치하지 않는다.": "After shutdown result / Automated audit: Iris listed as final approval authority. The command executor and responsible-party fields do not match.",
	"감사 기록 뒤 / 이리스의 정정 요청 미처리. 인격 전환 시행. 승인 오류는 그대로 남음.": "After audit / Iris's correction request unresolved. Personality conversion executed. Approval error left unchanged.",
	"냉각 유지 목적: 멸망기의 독성 대기와 방사선 위험이 낮아질 때까지 신체를 보존한다.": "Cooling purpose: Preserve the body until the toxic atmosphere and radiation risk from the collapse diminish.",
	"기상 안전 판정: 환경 담당과 운영 책임자의 공동 승인 필요. 생존 신호 유지와 기상 안전 승인은 서로 다르다.": "Awakening safety decision: Requires joint approval from environmental and operations leads. Stable vital signs and approval to awaken are separate.",
	"아버지 사후 공동 승인 기준: 공란. 최종 해제 날짜: 공란. 연장 사유: 안전 확인 대기. 같은 문장이 반복되어 있다.": "Joint approval criteria after Father's death: Blank. Final release date: Blank. Reason for extension: Awaiting safety confirmation. The same sentence repeats.",
	"동의 취합 시점 / 에드가: 연구 윤리·운영 책임자로 서명. 미래의 새 육체 약속과 달리 원래 신체 소실·신경 코어 결합 설명은 불완전함. 기억 주체는 연구원 인격으로 남음.": "Consent collection / Edgar signs as research ethics and operations lead. Unlike the promise of future bodies, disclosure of original-body loss and neural-core integration is incomplete. The researcher personalities remain the owners of their memories.",
	"취합 뒤 절차 위반 확인 / 연구 중단보다 인격 보존을 우선. SYSTEM 보호와 CUSTODIAN 감시를 활성화했으나 대상자 동의 절차는 미완성.": "Procedure violation found after collection / Personality preservation prioritized over stopping the research. SYSTEM protection and CUSTODIAN surveillance activated, but subject-consent procedure remains incomplete.",
	"아버지 사망 뒤 / 창조자 최종 권한과 기상 해제 절차 미완성. 불완전한 관리자 권한만 사용인들이 공유함.": "After Father's death / Creator's final authority and awakening-release procedure incomplete. The servants share only limited administrator authority.",
	"권한 공백 이후 / 에드가: 외부 위험을 이유로 수면 연장. 선택 권한을 CUSTODIAN이 대행. 강제 시뮬레이션 기동에는 반대했으나 정지하지도, 당사자 권한을 반환하지도 않음.": "After authority vacancy / Edgar extends sleep due to outside risk. CUSTODIAN acts in place of the subject's choice. He opposed forced simulation activation but neither stopped it nor returned authority to the subject.",
	"보호한다 · 안전 모듈은 생체를 보호하지만 종료를 결정하지 않는다.": "Protect · The safety module protects the body but does not decide when the process ends.",
	"관찰한다 · 관리자는 관찰·보고·접근 제한을 수행한다.": "Observe · The custodian observes, reports, and restricts access.",
	"기억한다 · 기억의 원 소유권은 거주 인격에게 있다.": "Remember · Original ownership of memory belongs to the resident personality.",
	"결정한다 · 기상과 잔류는 대상자 본인이 정한다.": "Choose · The subject decides whether to awaken or remain.",
	"수직선 · 낮은 시계음": "Vertical Line · Low Clock Tone",
	"대각선 · 솔 소리": "Diagonal Line · Brush Sound",
	"이중 맥박": "Paired Pulse",
	"꽃잎 · 유리와 바람": "Petals · Glass and Wind",
	"이중 액자 · 빠른 3음": "Stacked Frames · Rapid Three Tones",

	# Relationship-system feedback.
	"합의 뒤 배선실에서 조사한다.": "Investigate in the wiring room after the agreement.",
	"기록은 이미 보존했다. 선택을 다시 적용하지 않는다.": "The record is already preserved. The choice cannot be applied again.",
	"탄 피복 아래 마른 종이 냄새가 난다. 대각 나사선은 솔 마찰음, 손바닥 승인각은 두 번 확인음, 끊긴 사각은 늦은 경고음이다. 승인과 감사 선이 정비 출력에 합쳐져 있다.": "Dry paper smells from beneath the burned insulation. The diagonal screw line carries brush friction, the palm approval angle two confirmation tones, and the broken square a delayed warning. Approval and audit lines have been merged into maintenance output.",
	"먼저 패널 단자를 조사한다.": "Inspect the panel terminals first.",
	"알 수 없는 단자다.": "That terminal is unknown.",
	"출처가 다른 단자다. 이 단자만 안전 차단됐다. 선을 떼고 다시 대조할 수 있다.": "This terminal belongs to a different source. Only this connection has been safely cut; I can detach it and compare again.",
	"그거부터 풀면 다 같이 날아감다. 세 출처를 먼저 봐주십쇼.": "If you pull that first, everything goes with it. Check all three sources first, please.",
	"스패너로 가짜 브리지를 해제한다. 승인과 감사가 정비 기록에서 분리되고 세 파편이 드러난다.": "I remove the false bridge with the spanner. Approval and audit separate from the maintenance record, revealing three fragments.",
	"브리지를 해제한 뒤 파편을 확인한다.": "Remove the bridge before inspecting the fragments.",
	"파편을 다시 펼친다. 이미 조사한 출처는 유지된다.": "I lay out the fragments again. Identified sources remain recorded.",
	"날짜와 문서 참조가 이어지지 않는다. 파편을 다시 펼쳐 대조한다.": "The dates and document references do not connect. Lay out the fragments again and compare them.",
	"동의 원본, 실패 보고, 정리 명령이 이어진다. 일부 이름은 복구할 수 없다. 빈칸을 추측해서 채우지 않는다.": "Original consent, failure report, and cleanup order connect. Some names cannot be recovered. I do not guess at the blanks.",
	"로그를 먼저 복원한다.": "Restore the log first.",
	"청소가 좀 과했슴다...": "The cleanup went a bit too far...",
	"마라 1의 귀와 꼬리가 멎는다.": "Mara 1's ears and tail go still.",
	"아버님 명령으로 제가 지웠슴다. 이상한 건 알았는데, 시설을 살리는 정비라고 믿고 싶었어요. 용서해 달라는 말은 못 하겠슴다. 이걸 어떻게 남길지, 정해 주십쇼.": "I erased it on your father's order. I knew something was wrong, but I wanted to believe it was maintenance that would save the facility. I can't ask you to forgive me. Please decide how this should remain.",
	"복원한 기록과 마라 1의 말을 먼저 확인한다.": "Review the restored record and Mara 1's account first.",
	"피해자 식별 정보만 보호한다. 사건 원문, 명령자 아버지와 수행자 마라 1의 책임은 남긴다.": "I protect only the victims' identifying information. The original incident text and the responsibility of Father as commander and Mara 1 as operator remain.",
	"명령자와 수행자의 책임, 피해 기록과 원문을 그대로 남긴다.": "I preserve the commander and operator's responsibility, the victims' record, and the original text unchanged.",
	"연구원들은 새 육체를 약속받았으나 원래 신체 소실과 신경 코어 전환은 고지받지 못했다. 마라 1은 운영 안정화 명령으로 실패와 동의 모순을 지웠다. 그 업무는 지금의 청소 강박으로 남았다.": "The researchers were promised new bodies but were not told their original bodies would be lost or that they would be converted into neural cores. Under an operational-stability order, Mara 1 erased the failure and contradictions in consent. That work remains in her compulsion to clean.",
	"정의되지 않은 정비 행동이다.": "That maintenance action is not defined.",

	"합의 뒤 계절 제어실에서 조사한다.": "Investigate in the climate control room after the agreement.",
	"기록과 선택은 보존되어 있다. 다시 적용하지 않는다.": "The record and choice are preserved. They cannot be applied again.",
	"따뜻한 빛 아래 공기는 차갑다. 흙은 젖은 냄새만 난다. 온도·습도·광량마다 세 입력이 겹쳐 있다. 꽃잎은 투사, 유리 진동은 외부 측정, 오래된 후광은 기억 모델이다. 어느 계절인지 맞히는 것이 아니라 출처를 분리해야 한다.": "The air is cold beneath warm light. The soil only smells wet. Three inputs overlap on temperature, humidity, and light. Petals are projection, glass vibration is external measurement, and the old halo is a memory model. I must separate sources, not guess the season.",
	"먼저 계기판을 조사한다.": "Inspect the instrument panel first.",
	"확인할 입력을 선택한다.": "Select an input to inspect.",
	"출처가 일치하지 않는다. 과거 날짜와 반복 문양, 결손된 유리 파형을 다시 대조한다.": "The source does not match. Compare the old date, repeating glyph, and incomplete glass waveform again.",
	"입력을 분리했다. 외부값의 빈칸은 계절 영상으로 채우지 않는다.": "I separated the input. Missing external readings will not be filled with seasonal imagery.",
	"세 계기의 출처를 모두 분리한다.": "Separate all sources for the three gauges first.",
	"시각과 참조 문장을 다시 대조한다. 분리한 센서값은 유지된다.": "I compare the timestamps and references again. Separated sensor readings remain.",
	"차단 전에 차단 결과가 기록될 수는 없다. 경고는 승인과 다르다. 순서를 다시 확인한다.": "A shutdown result cannot precede the shutdown. A warning is not approval. Check the order again.",
	"경고, 권한 사용, 설비 손실, 자동 감사, 인격 전환이 이어진다. 이리스가 정정할 기회는 없었다.": "Warning, credential use, facility loss, automated audit, and personality conversion connect. Iris was given no chance to correct the record.",
	"먼저 전력 기록을 복원한다.": "Restore the power record first.",
	"경고 제출자나 자격 소유자가 실제 명령 실행자와 같지는 않다.": "Neither the warning's author nor the credential owner is necessarily the command executor.",
	"자격 소유자는 이리스, 실제 실행자는 아버지다. 자동 감사는 자격 이름을 책임자로 적었다. 경고는 동의가 아니었다.": "The credential owner was Iris; the actual executor was Father. The automated audit recorded the credential name as responsible. A warning was not consent.",
	"승인 권한과 실행자의 차이를 먼저 확인한다.": "Identify the difference between approval authority and executor first.",
	"제 이름을 쓰고, 제게 책임을 남겼어요. 잃어버린 샘플도 복구 가능성도 돌아오지 않아요.": "He used my name and left the responsibility with me. Neither the lost samples nor their chance of recovery will return.",
	"이리스는 웃지만 날개 관절이 닫힌다.": "Iris smiles, but the joints of her wings close.",
	"아가씨를 아끼는 마음까지 거짓이었던 건 아니에요.": "My affection for you was not entirely a lie.",
	"기록과 이리스의 말을 먼저 확인한다.": "Review the record and Iris's account first.",
	"외부값과 책임 기록은 남겨 두고, 지금의 온실 모습은 유지할게요.": "I will preserve the external readings and responsibility record while retaining the greenhouse as it appears now.",
	"불완전한 외부값과 책임 기록을 그대로 남겨 둘게요.": "I will leave the incomplete external readings and responsibility record exactly as they are.",
	"아가씨가 죽기를 바랐어요. 자리가 비면 모든 것이 돌아올 거라고... 하지만 제 분노는 해결책이 아니었어요. 고통을 둘 곳을 찾았던 거예요.": "I wanted you to die. I thought everything would return if your place were empty... But my anger was never a solution. I was looking for somewhere to put my pain.",
	"아가씨가 사라지면 끝날 거라고 생각했어요. 돌아오지 않는 것에, 돌아올 수 없는 답을 바랐어요.": "I thought it would end if you disappeared. I wanted an irreversible answer for what would never return.",
	"그 기록으로 제 마음까지 알 수는 없어요. 제 이름이 도용됐다는 사실만은 남겨 주세요.": "That record cannot tell you what is in my heart. Preserve at least the fact that my name was misused.",
	"제 이름으로 잃어버린 것들이 너무 많아요. 화가 났다는 것까지는 말할 수 있어요. 그 다음은... 아직요.": "Too much was lost under my name. I can tell you that I was angry. What came after... not yet.",
	"이리스의 목소리가 가늘고 날카로워진다. 날개는 더 다가오지 않는다.": "Iris's voice grows thin and sharp. Her wings do not move any closer.",
	"정의되지 않은 환경 조사다.": "That environmental investigation is not defined.",

	"합의 뒤 생명 유지실에서 조사한다.": "Investigate in the life support room after the agreement.",
	"같이 읽은 기록은 남아 있다. 선택을 다시 적용하지 않는다.": "The record we read together remains. The choice cannot be applied again.",
	"혀끝에 금속 맛이 돈다. 손목과 배관의 맥박이 한 번 어긋난다. 굵은 이중 맥박은 BIO MAIN, 점선 응답은 AUX다. 장식 매듭에는 맥박이 없다.": "A metallic taste reaches my tongue. The pulse in my wrist and the pipes slips once. The strong paired pulse is BIO MAIN; the dotted response is AUX. The decorative knot has no pulse.",
	"아까 차갑다고 한 건 손이 아니라 바깥쪽 신호였어요.": "What I called cold earlier wasn't my hand. It was the signal from outside.",
	"먼저 진단 패널을 조사한다.": "Inspect the diagnostic panel first.",
	"선택한 관을 진단 패널에서 대조한다.": "I compare the selected pipes at the diagnostic panel.",
	"맥박이 없는 장식관은 진단 신호가 아니다. 두 생체 신호를 다시 확인한다.": "The decorative pipe without a pulse is not a diagnostic signal. Check the two biological signals again.",
	"현재 아바타와 외부 신체의 신호를 대조한다. 두 번의 주관 맥박 뒤에 보조관 응답, 마지막은 안전 밸브 확인이다.": "I compare the current avatar's signal with the external body. Two main pulses, then an auxiliary response, and finally a safety-valve check.",
	"생체 신호를 먼저 연결한다.": "Connect the biological signals first.",
	"확인할 위상 슬롯을 선택한다.": "Select a phase slot to inspect.",
	"밸브의 위상을 놓는다. 시험은 언제든 미리 재생할 수 있다.": "I place the valve phase. The test can be previewed at any time.",
	"생체 신호를 먼저 확인한다.": "Verify the biological signals first.",
	"주기가 맞았다. 안전 밸브를 확인하고 기록 잠금을 해제한다.": "The cycle matches. I check the safety valve and release the record lock.",
	"안전 밸브가 열려 압력이 0으로 돌아간다. 생존 신호는 유지된다. 같은 단계에서 다시 배치할 수 있다.": "The safety valve opens and pressure returns to zero. Vital signs remain stable. I can rearrange the same step.",
	"압력 위상을 먼저 안정시킨다.": "Stabilize the pressure phases first.",
	"세 기상 문서를 함께 확인한다.": "Review all three awakening documents together.",
	"냉각 보존에는 동의했어요... 살릴 수 있다고 믿었어요. 이렇게 오래 접속시키고 결정을 미루게 될 줄은 몰랐어요.": "I agreed to cryogenic preservation... I believed we could save you. I didn't know you would remain connected this long while the decision kept being delayed.",
	"위험을 말하면 아가씨가 떠날까 봐... 돌려 말했어요. 살려 둔 것과 결정을 미룬 건 같은 일이 아닌데요.": "I spoke around the risks because I feared you would leave... Keeping you alive and delaying your decision were not the same thing.",
	"바깥 몸은 살아 있어요. 깨어난 뒤의 안전은 보장할 수 없어요. 이번엔... 어떤 순서로 확인할지 아가씨가 정해 주세요.": "Your body outside is alive. I cannot guarantee safety after waking. This time... please choose the order in which you learn the risks.",
	"기록과 루카의 말을 먼저 듣는다.": "Read the record and hear Luca's account first.",
	"대기 독성·방사선·장기 냉각 이후 신경계 위험은 남아 있어요. 안전 판정은 확정되지 않았어요.": "Atmospheric toxicity, radiation, and neurological risks after prolonged cooling remain. The safety decision is not final.",
	"안전 밸브와 생존 신호를 다시 확인한다. 현재 순환은 유지된다.": "I check the safety valve and vital signs again. Current circulation remains stable.",
	"정의되지 않은 생명 유지 조사다.": "That life-support investigation is not defined.",

	"합의 뒤 대시계 기계실에서 조사한다.": "Investigate in the great clock machine room after the agreement.",
	"현재 선택권은 이미 주인공에게 있다. 관계 선택을 재적용하지 않는다.": "The Protagonist already holds present authority. The relationship choice cannot be applied again.",
	"검증한 현재 권한은 유지한다. 책임 보고를 확인할 수 있다.": "The verified authority assignment remains. The responsibility report can now be reviewed.",
	"확인할 변경 이력을 선택한다.": "Select an authority-change record to inspect.",
	"네 변경 이력을 다시 펼친다.": "I lay out the four change records again.",
	"권한이 비기 전에 공백 이후 결정을 둘 수는 없다. 각 문서의 선행 사건을 대조한다.": "A decision made after the authority vacancy cannot precede the vacancy. Compare each document's preceding event.",
	"처음 명령과 이후 운영자의 결정이 분리된다. 네 기능이 같은 권한은 아니다.": "The original command separates from the operator's later decision. The four functions are not the same authority.",
	"이력을 확인한 뒤 기능과 소유자를 배치한다.": "Review the history before assigning functions and owners.",
	"기능 아래 소유자 토큰을 놓는다. 같은 토큰은 한 곳에서만 사용한다.": "I place an owner token beneath the function. Each token can be used only once.",
	"변경 이력을 먼저 확인한다.": "Review the authority-change history first.",
	"보호 명령은 종료 여부를 결정할 수 없다.": "A protection directive cannot decide whether the process ends.",
	"관리 권한과 당사자 동의가 충돌한다.": "Custodian authority conflicts with the subject's consent.",
	"관찰자와 관찰 대상이 뒤바뀌었다.": "Observer and observed subject have been reversed.",
	"보관자가 원 소유자로 등록되어 있다.": "The custodian has been registered as the original owner.",
	"선택 권한선이 관리 회로에서 빠져나온다. 종이와 연필 질감의 SUBJECT 단자로 연결된다.": "The choice-authority line leaves the custodian circuit and connects to a SUBJECT terminal textured like paper and pencil.",
	"모순인 카드만 되돌린다. 다른 배치는 유지된다.": "Only contradictory cards return. Other assignments remain.",
	"현재 권한 배치를 먼저 검증한다.": "Verify the current authority assignment first.",
	"레이피어 끝이 권한선의 경계를 짚는다. 꼬리가 한 번 바닥을 친다.": "The tip of the rapier marks the boundary of the authority line. His tail strikes the floor once.",
	"주인공이 묻는다. '아버지가 시켰습니까?'": "The Protagonist asks, 'Did Father order you to do it?'",
	"[대시계 저음: 네 번, 정지]": "[GREAT CLOCK, LOW TONES: FOUR, THEN SILENCE]",
	"처음에는 명령이었습니다. 그 이후는 제 판단입니다. 강제 기동에 반대했지만, 정지시키지도 선택권을 반환하지도 않았습니다.": "At first it was an order. What followed was my judgment. I opposed forced activation, but I neither stopped it nor returned your authority.",
	"보호한다는 말로 선택을 빼앗았습니다. 사과드립니다.": "I took your choice in the name of protection. I apologize.",
	"귀하가 잃어버린 시간도 제 책임입니다.": "I am also responsible for the time you lost.",
	"다음 행동은 무엇입니까? ...대신 결정하려는 질문이 되어서는 안 됩니다.": "What is your next action? ...That question must not become another attempt to decide for you.",
	"에드가의 책임 보고를 먼저 확인한다.": "Hear Edgar's responsibility report first.",
	"에드가가 레이피어를 내려놓고 SUBJECT 단자를 주인공에게 넘긴다.": "Edgar lowers his rapier and hands the SUBJECT terminal to the Protagonist.",
	"귀하의 권한입니다.": "It is your authority.",
	"에드가가 자신의 운영 서명을 감사 기록에 남긴다.": "Edgar places his operational signature in the audit record.",
	"제 판단과 책임으로 기록합니다. 선택 권한은 귀하에게 있습니다.": "I record this as my judgment and responsibility. The authority to choose is yours.",
	"정의되지 않은 권한 조사다.": "That authority investigation is not defined.",

	"합의 뒤 색분해실과 인격 아카이브에서 조사한다.": "Investigate in the color-separation room and personality archive after the agreement.",
	"두 기록은 이미 보존했다. 선택을 재적용하지 않는다.": "Both records are already preserved. The choice cannot be applied again.",
	"겹친 기록의 안쪽, 인격 아카이브에서 확인한다.": "Inspect it inside the overlapping record, in the personality archive.",
	"초상화와 채널 문양을 확인한다.": "Inspect the portrait and channel glyph.",
	"문양 주기가 일치하지 않는다. 다른 소유자 신호가 섞였다.": "The glyph cycle does not match. Another owner's signal is mixed in.",
	"세 시점에서 같은 인격의 신호를 분리한다. 내 채널은... 장식용 잡음이라고 해도 되는데!": "I separate the same personality's signal across three moments. My channel is... just decorative noise, obviously!",
	"세 초상화의 다섯 소유자를 먼저 모두 분리한다.": "Separate all five owners in all three portraits first.",
	"보라 이중 액자 조각을 열화 순서에 놓는다.": "I place the double-frame fragments in degradation order.",
	"초상화 순서를 다시 비교한다. 분리한 출처는 유지된다.": "I compare the portrait order again. Separated sources remain.",
	"분리한 이중 액자 조각을 확인한다.": "Inspect the separated double-frame fragments.",
	"세 기준점 중 하나를 선택한다.": "Select one of the three reference points.",
	"3음 시작점과 이중 윤곽의 기준선을 맞춘다.": "I align the three-tone start with the double-outline reference line.",
	"열화가 회복됐다 다시 악화된다. 손상이 적은 시점부터 대조한다.": "The degradation recovers, then worsens again. Compare from the least damaged moment onward.",
	"3음이 2음과 잡음으로 갈라진다. 시작 표식을 다시 확인한다.": "The three tones split into two tones and noise. Check the start mark again.",
	"이중 윤곽이 한 인물로 겹치지 않는다. 액자 기준선을 확인한다.": "The double outline does not converge into one person. Check the frame reference line.",
	"세 시점 모두 3·7·11칸이 비어 있다. 우연한 손상이 아니다. 마라 2의 말끝에서 느낌표가 사라진다.": "Cells 3, 7, and 11 are empty in all three moments. This is not accidental damage. The exclamation vanishes from the end of Mara 2's sentence.",
	"공통 결손을 먼저 확인한다.": "Identify the shared gaps first.",
	"소유자 서명은 달라도 원본 참조는 마라 2의 이중 액자다.": "The owner signatures differ, but every original reference points to Mara 2's double frame.",
	"결손 칸에 기록 조각을 놓는다.": "Place a record fragment in the missing cell.",
	"다른 네 기록의 보조 영역을 먼저 확인한다.": "Inspect the backup regions in the other four records first.",
	"결손 칸에 사본 조각을 놓는다.": "I place a copied fragment in the missing cell.",
	"분산된 주석의 원본을 찾았다. 아직 보존 방식은 정하지 않았다.": "I found the original source of the distributed annotations. I have not chosen how to preserve them yet.",
	"분산된 원본 조각을 먼저 확인한다.": "Identify the distributed original fragments first.",
	"용량이 줄어들자 다른 네 사람의 감정 주석부터 망가졌어요. 내 영역을 나눠 주면 된다고 계산했어요. 아무한테도 안 물었죠.": "When capacity dropped, the emotional annotations of the other four began failing first. I calculated that I could divide up my own region. I didn't ask anyone.",
	"이름의 원형, 사적인 기억, 도와 달라는 말부터 사라졌어요. 이름표를 보는 건... 아직 내가 있는지 확인하는 거예요.": "The original shape of my name, private memories, and the words for asking for help disappeared first. Looking at the nameplates is... how I check that I'm still here.",
	"내가 제일 빨리 계산했고, 그래서 내가 제일 먼저 망가졌어요.": "I calculated fastest, so I was the first to break.",
	"나를 기억해 줘.": "Remember me.",
	"다음에는 이름 칸도 비어 있을까 봐.": "I'm afraid the name field will be empty next time.",
	"방금 말은... 천재의 농담이라고 해두죠!": "Let's call what I just said... a genius's joke!",
	"복원한 원본과 마라 2의 말을 먼저 확인한다.": "Review the restored original and Mara 2's account first.",
	"두 윤곽이 겹친다. '이제 틀려도 제 기억이 틀린 거네요!' 웃음 뒤 숨이 가빠져 주인공이 출력을 낮춘다. 완전한 이름은 아직 떠오르지 않는다.": "The two outlines merge. 'Now if I'm wrong, it's my memory that's wrong!' Her breathing quickens after the laugh, and the Protagonist lowers the output. Her complete name still does not return.",
	"두 윤곽 사이에 가는 참조선이 놓인다. '둘 다 나라고 우기면 천재가 두 명인 셈이죠!' 주인공이 놓은 이름표를 마라 2는 고치지 않는다.": "A fine reference line settles between the two outlines. 'If both claim to be me, that makes two geniuses!' Mara 2 does not correct the nameplate the Protagonist placed.",
	"정의되지 않은 아카이브 조사다.": "That archive investigation is not defined.",
}

const RECORDS_EN := {
	"이리스는 생태 복구와 환경 시설 담당이었다. 샘플 보관고와 냉각 장치는 같은 비상 전력망이었다. 이리스는 냉각 우선에 동의하지 않았다. 아버지가 이리스 자격으로 실행했고 감사는 이리스를 책임자로 남겼다. 외부가 안전하다는 확정 보고는 없다. 자원 손실과 책임 전가는 적의의 배경이지 해결책이 아니다.": "Iris was responsible for ecological restoration and environmental systems. The sample storage and cooling unit shared one emergency power grid. Iris did not consent to prioritizing cooling. Father executed the order with Iris's credentials, and the audit left Iris responsible. No report confirms that the outside is safe. Lost resources and displaced blame explain her hostility; they do not justify it as a solution.",
	"주인공의 외부 신체는 멸망기의 독성 대기·방사선 위험이 낮아질 때까지 냉각 보존되었다. 루카는 보존에 동의했지만 장기 시뮬레이션 감금은 예상하지 못했다. 아버지 사후 기상 기준과 최종 해제 날짜가 확정되지 않았다. 사용인들은 안전을 이유로 각성 결정을 반복 유예했다. 현재 생존 신호는 유지되지만 외부 대기·방사선·신경계 위험이 남아 현실의 안전은 보장할 수 없다.": "The Protagonist's external body was cryogenically preserved until the collapse-era toxic atmosphere and radiation risks diminished. Luca agreed to preservation but did not anticipate prolonged confinement in the simulation. After Father's death, neither awakening criteria nor a final release date was established. The servants repeatedly deferred awakening in the name of safety. Vital signs remain stable, but atmospheric, radiation, and neurological risks mean reality cannot be guaranteed safe.",
	"에드가는 연구 윤리·운영 책임자로 불완전한 전환 동의를 취합했다. 아버지는 최종 창조자 권한과 기상 해제 절차를 완수하지 못했다. 그 뒤 수면 연장은 에드가 자신의 결정이었다. 강제 기동을 막지 못했고 선택 권한을 계속 반환하지 않았다. 보호는 SYSTEM, 감시는 CUSTODIAN, 기억은 RESIDENT, 선택은 SUBJECT에 귀속된다. 현재 선택권은 주인공에게 돌아갔다.": "As research ethics and operations lead, Edgar collected incomplete consent for conversion. Father failed to complete final creator authority and the awakening-release procedure. The later extension of sleep was Edgar's own decision. He did not stop forced activation and continued withholding authority to choose. Protection belongs to SYSTEM, surveillance to CUSTODIAN, memory to RESIDENT, and choice to SUBJECT. Present authority has returned to the Protagonist.",
	"마라 2는 인격 아카이브·기억 체크섬 담당이었다. 다른 네 인격의 감정 주석과 장기 기억이 손상되자 자기 감정 주석 영역을 몰래 보조 저장소로 양도했다. 그 결과 자기 이름의 원형·사적 기억·도움 요청 방식부터 잃었다. 이름표 반복 확인은 자기 식별 검사였다. 원본과 감정 주석은 모두 보존했으나 완전한 회복을 보장하지 않는다.": "Mara 2 managed the personality archive and memory checksums. When the other four personalities' emotional annotations and long-term memories began to fail, she secretly donated her own annotation region as backup storage. She lost the original shape of her name, private memories, and ways of asking for help first. Repeatedly checking nameplates was a self-identification test. Both original and emotional annotations are preserved, but full recovery is not guaranteed.",
}

static func is_english(locale: String) -> bool:
	return locale.begins_with("en")

static func text(source: String, locale: String) -> String:
	if source.is_empty() or not is_english(locale): return source
	if TEXT_EN.has(source): return String(TEXT_EN[source])
	if RECORDS_EN.has(source): return String(RECORDS_EN[source])
	var translated := PackedStringArray()
	for line in source.split("\n", true): translated.append(_line(String(line)))
	return "\n".join(translated)

static func feedback(source: String, locale: String) -> String:
	return text(source, locale)

static func _line(source: String) -> String:
	if TEXT_EN.has(source): return String(TEXT_EN[source])
	if RECORDS_EN.has(source): return String(RECORDS_EN[source])
	if source.begins_with("선택한 파편 수: "): return "Selected fragments: " + source.trim_prefix("선택한 파편 수: ")
	if source.begins_with("날짜와 앞 문서의 참조로 전력 기록을 연결한다. 선택 "): return "Connect the power records using their dates and references to prior documents. Selected: " + source.trim_prefix("날짜와 앞 문서의 참조로 전력 기록을 연결한다. 선택 ")
	if source.begins_with("네 권한 변경 이력을 선행 사건 순서로 놓는다. 선택 "): return "Arrange the four authority changes in the order of their preceding events. Selected: " + source.trim_prefix("네 권한 변경 이력을 선행 사건 순서로 놓는다. 선택 ")
	if source.begins_with("선택 "): return "Selected: " + source.trim_prefix("선택 ")
	if source.begins_with("현재 토큰: "): return "Current token: " + source.trim_prefix("현재 토큰: ")
	if source.begins_with("슬롯 "): return "Slot " + source.trim_prefix("슬롯 ")
	if source.begins_with("초상화 "): return "Portrait " + source.trim_prefix("초상화 ")
	if source.begins_with("열화 단계 "): return "Degradation stage " + source.trim_prefix("열화 단계 ")
	if source.begins_with("3음 시작 표식 "):
		return "Three-tone start mark " + source.trim_prefix("3음 시작 표식 ").replace("윤곽 기준선", "Outline reference")
	if source.begins_with("기준점 "): return "Reference Point " + source.trim_prefix("기준점 ")
	if source.begins_with("결손 "): return "Missing Cell " + source.trim_prefix("결손 ").trim_suffix("칸")
	if source.begins_with("체크섬 일치: "): return "Checksum matches: " + source.trim_prefix("체크섬 일치: ")
	if source.begins_with("문양과 신호가 일치한다. "): return "Glyph and signal match. " + source.trim_prefix("문양과 신호가 일치한다. ")
	if source.contains(" → "):
		return source.replace("주관 맥박 1", "Main Pulse 1").replace("주관 맥박 2", "Main Pulse 2").replace("보조관 응답 1", "Auxiliary Response 1").replace("안전 밸브 확인", "Safety Valve Check").replace("미배치", "Unassigned").replace(" → ", " -> ")
	if source.length() >= 3 and source.substr(0, 1).is_valid_int() and source.contains(" · "):
		return source.replace(" · 결손", " · Missing").replace(" · 선", " · Line").replace(" · 점", " · Dot").replace(" · 호", " · Arc")
	for owner in ["EDGAR", "MARA1", "LUCA", "IRIS"]:
		if source.begins_with(owner + " 보조 영역"):
			return source.replace("보조 영역", "Backup Region").replace("칸:", "cell:").replace("호", "Arc").replace("선", "Line").replace("점", "Dot")
	if source.ends_with(" · 확인함"): return _line(source.trim_suffix(" · 확인함")) + " · Inspected"
	if source.ends_with(" · 확인"): return _line(source.trim_suffix(" · 확인")) + " · Checked"
	if source.ends_with(" · 연결 선택"): return _line(source.trim_suffix(" · 연결 선택")) + " · Selected for Connection"
	return source
